[package]
name = "sbox-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.1", default-features = false, features = ["json"] }
diesel = { version = "1.4.4", features = ["postgres"] }
dotenv = "0.15.0"
diesel_migrations = "1.4.0"
serde = "1.0.127"
schemars = "0.7"
rocket_okapi = { version = "0.8.0-alpha-1", url = "https://github.com/GREsau/okapi/tree/master/rocket-okapi", features = ["swagger", "rapidoc"] }

[dependencies.rocket_dyn_templates]
version = "0.1.0-rc.1"
features = ["handlebars", "tera"]

[dependencies.tera]
version = "^1"
default-features = false
