[package]
name = "sbox-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
diesel_migrations = "1.4.0"
serde = "1.0.127"
schemars = "0.7"
okapi = "0.6.0-alpha-1"

[dependencies.rocket]
version = "0.5.0-rc.1"
default-features = false
features = ["json"]

[dependencies.rocket_sync_db_pools]
version = "0.1.0-rc.1"
features = ["diesel_postgres_pool"]

[dependencies.rocket_okapi]
version = "0.8.0-alpha-1"
url = "https://github.com/GREsau/okapi/tree/master/rocket-okapi"
features = ["swagger", "rapidoc"]

[dependencies.diesel]
version = "1.4.4"
features = ["postgres"]
